### ISSUE TITLE
Package not in composer

### ISSUE THREAD

**Issue by Firesphere** [axyr/silverstripe-console#2]
```
  Could not find package axyr/silverstripe-console at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability  
```

I think you'll need to register it, or enable the webhook. I'm running into similar issues with other modules btw.

**Comment by axyr** [comment]
Yeah, thats correct. its not on composer yets.

Will add it, but there is more to make this module working in an easy way.

also not all documented featerues are implemented yet..

Thanks for the interest!!
