### ISSUE TITLE
Add tests functionality

### ISSUE THREAD

**Issue by Firesphere** [axyr/silverstripe-console#3]
Adding tests would be nice. It's currently missing.

**Comment by axyr** [comment]
you mean the UnitTests?
There is currently only one ?

https://github.com/axyr/silverstripe-console/tree/master/tests

**Comment by Firesphere** [comment]
No, I mean the option to do php sake tests:mytest

**Comment by axyr** [comment]
yeah. will add that as well.

Good find!
